version: "3.8" # You can adjust the version depending on your Docker Compose setup

services:
  vllm:
    image: vllm/vllm-openai:YOUR_TAG
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=YOUR_TOKEN
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: |
      --model YOUR_MODEL
      --max-model-len YOUR_LENGTH
      --dtype=YOUR_TYPE
      --api-key YOUR_KEY
