version: "3.8" # You can adjust the version depending on your Docker Compose setup

services:
  vllm:
    image: vllm/vllm-openai:v0.6.4.post1
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=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
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: |
      --model meta-llama/Llama-3.2-3B-Instruct
      --max-model-len 8192
      --api-key jack1234
    restart: always
# Mark --dtype=YOUR_TYPE
