version: "3.8" # You can adjust the version depending on your Docker Compose setup

services:
  vllm:
    image: vllm/vllm-openai:v0.6.4.post1
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=YOUR_TOKEN
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: |
      --model YOUR_MODEL
      --max-model-len YOUR_LEN
      --api-key YOUR_APIKEY
    restart: always
# Mark --dtype=YOUR_TYPE
