version: "3.8"

services:
  vllm:
    image: IMAGE_REPO:TAG
    privileged: true
    environment:
      - HUGGING_FACE_HUB_TOKEN=YOUR_TOKEN
      - VLLM_CPU_KVCACHE_SPACE=12
      - VLLM_CPU_OMP_THREADS_BIND=0-7      
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    command: |
      --model YOUR_MODEL
      --max-model-len YOUR_LEN
      --api-key YOUR_APIKEY
    restart: always
    ipc: host
